/**********************************************************
Program Name: BurgersRUsGUI.java 
Programmer's Name: Daniel F Diaz Santiago 
Program Description: This program creates burger orders for
                     customers.
***********************************************************/


import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class BurgersRUsGUI extends javax.swing.JFrame {
    private double order_total;
    /**
     * Creates new form BurgersRUsGUI
     */
    public BurgersRUsGUI() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        order_total = 0.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        double_btn = new javax.swing.JRadioButton();
        single_btn = new javax.swing.JRadioButton();
        cheese_check = new javax.swing.JCheckBox();
        meal_check = new javax.swing.JCheckBox();
        bacon_check = new javax.swing.JCheckBox();
        price_lbl = new javax.swing.JLabel();
        price_box = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_box = new javax.swing.JTextArea();
        order_lbl = new javax.swing.JLabel();
        qty_lbl = new javax.swing.JLabel();
        qty_box = new javax.swing.JTextField();
        total_lbl = new javax.swing.JLabel();
        total_box = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_file = new javax.swing.JMenu();
        mnu_exit = new javax.swing.JMenuItem();
        mnu_order = new javax.swing.JMenu();
        mnu_add_to = new javax.swing.JMenuItem();
        mnu_clear = new javax.swing.JMenuItem();
        mnu_new = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_group.add(double_btn);
        double_btn.setText("Double Burger");
        double_btn.setNextFocusableComponent(cheese_check);
        double_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                double_btnActionPerformed(evt);
            }
        });

        btn_group.add(single_btn);
        single_btn.setText("Single Burger");
        single_btn.setNextFocusableComponent(double_btn);
        single_btn.setOpaque(true);
        single_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                single_btnActionPerformed(evt);
            }
        });

        cheese_check.setText("Add cheese");
        cheese_check.setNextFocusableComponent(bacon_check);
        cheese_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheese_checkActionPerformed(evt);
            }
        });

        meal_check.setText("Make it a meal");
        meal_check.setNextFocusableComponent(price_box);
        meal_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_checkActionPerformed(evt);
            }
        });

        bacon_check.setText("Add Bacon");
        bacon_check.setNextFocusableComponent(meal_check);
        bacon_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacon_checkActionPerformed(evt);
            }
        });

        price_lbl.setText("Item Price");

        price_box.setEditable(false);
        price_box.setText("0");
        price_box.setNextFocusableComponent(qty_box);

        order_box.setColumns(20);
        order_box.setRows(5);
        order_box.setFocusable(false);
        jScrollPane1.setViewportView(order_box);

        order_lbl.setText("YOUR ORDER");

        qty_lbl.setText("Quantity");

        qty_box.setText("1");
        qty_box.setNextFocusableComponent(total_box);

        total_lbl.setText("Order Total");

        total_box.setEditable(false);
        total_box.setNextFocusableComponent(single_btn);

        mnu_file.setText("File");

        mnu_exit.setText("Exit");
        mnu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_exitActionPerformed(evt);
            }
        });
        mnu_file.add(mnu_exit);

        jMenuBar1.add(mnu_file);

        mnu_order.setText("Order");

        mnu_add_to.setText("Add to Order");
        mnu_add_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_add_toActionPerformed(evt);
            }
        });
        mnu_order.add(mnu_add_to);

        mnu_clear.setText("Clear for next item");
        mnu_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_clearActionPerformed(evt);
            }
        });
        mnu_order.add(mnu_clear);

        mnu_new.setText("New Order");
        mnu_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_newActionPerformed(evt);
            }
        });
        mnu_order.add(mnu_new);

        jMenuBar1.add(mnu_order);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(price_box, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(meal_check)
                    .addComponent(bacon_check)
                    .addComponent(cheese_check)
                    .addComponent(single_btn)
                    .addComponent(double_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qty_lbl)
                            .addComponent(total_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qty_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(order_lbl)
                            .addGap(112, 112, 112))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(order_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qty_lbl)
                            .addComponent(qty_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_lbl)
                            .addComponent(total_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(single_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(double_btn)
                        .addGap(18, 18, 18)
                        .addComponent(cheese_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bacon_check)
                        .addGap(18, 18, 18)
                        .addComponent(meal_check)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price_lbl)
                            .addComponent(price_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void double_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_double_btnActionPerformed
        update_item_price();
    }//GEN-LAST:event_double_btnActionPerformed

    private void cheese_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheese_checkActionPerformed
        update_item_price();
    }//GEN-LAST:event_cheese_checkActionPerformed

    private void mnu_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_clearActionPerformed
        clear_for_next_item();
    }//GEN-LAST:event_mnu_clearActionPerformed

    private void mnu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnu_exitActionPerformed

    private void single_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_single_btnActionPerformed
        update_item_price();
    }//GEN-LAST:event_single_btnActionPerformed

    private void bacon_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacon_checkActionPerformed
        update_item_price();
    }//GEN-LAST:event_bacon_checkActionPerformed

    private void meal_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_checkActionPerformed
        update_item_price();
    }//GEN-LAST:event_meal_checkActionPerformed

    private void mnu_add_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_add_toActionPerformed
        // Output line
        String output_line = qty_box.getText();
        if(single_btn.isSelected())
            output_line += " single";
        else
            output_line += " double";
        
        if(cheese_check.isSelected())
            output_line += ", cheese";
        if(bacon_check.isSelected())
            output_line += ", bacon";
        if(meal_check.isSelected())
            output_line += ", meal";
        
        output_line += " at ";
        output_line += price_box.getText();
        output_line += " each\n";
        
        order_box.append(output_line);
        
        // Update total
        int qty = Integer.parseInt(qty_box.getText());
        double item_price = Double.parseDouble(price_box.getText());
        double line_price = qty * item_price;
        
        order_total += line_price;
        DecimalFormat fmt = new DecimalFormat("#,##0.00");
        total_box.setText(fmt.format(order_total));
    }//GEN-LAST:event_mnu_add_toActionPerformed

    private void mnu_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_newActionPerformed
        clear_for_next_item();
        order_box.setText("");
        total_box.setText("");
        order_total = 0.0;
    }//GEN-LAST:event_mnu_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgersRUsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bacon_check;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JCheckBox cheese_check;
    private javax.swing.JRadioButton double_btn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox meal_check;
    private javax.swing.JMenuItem mnu_add_to;
    private javax.swing.JMenuItem mnu_clear;
    private javax.swing.JMenuItem mnu_exit;
    private javax.swing.JMenu mnu_file;
    private javax.swing.JMenuItem mnu_new;
    private javax.swing.JMenu mnu_order;
    private javax.swing.JTextArea order_box;
    private javax.swing.JLabel order_lbl;
    private javax.swing.JTextField price_box;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JTextField qty_box;
    private javax.swing.JLabel qty_lbl;
    private javax.swing.JRadioButton single_btn;
    private javax.swing.JTextField total_box;
    private javax.swing.JLabel total_lbl;
    // End of variables declaration//GEN-END:variables


    private void update_item_price(){
        double item_price = 0;
        
        if(single_btn.isSelected())
            item_price = 3.50;
        else if(double_btn.isSelected())
            item_price = 4.75;
        else{
            JOptionPane.showMessageDialog(this, "Burger type must be selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Add charges
        if(cheese_check.isSelected())
            item_price += 0.50;
        
        if(bacon_check.isSelected())
            item_price += 0.25;
        
        if(meal_check.isSelected())
            item_price += 4.00;
        
        DecimalFormat fmt = new DecimalFormat("#,##0.00");
        price_box.setText(fmt.format(item_price));
    }
    
    private void clear_for_next_item(){
        btn_group.clearSelection();
        cheese_check.setSelected(false);
        bacon_check.setSelected(false);
        meal_check.setSelected(false);
        price_box.setText("0");
        qty_box.setText("1");
    }
}
